# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets_generator', '0002_auto_20160217_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Foods', 'verbose_name_plural': 'Foods'},
        ),
    ]
