# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets_generator', '0004_auto_20160218_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='nutrient_highlight',
            field=models.CharField(max_length=1),
        ),
    ]
